FORMAT: 1A
HOST: https://d53d474e-ce2a-4121-a1a2-af2efa378e29.mock.pstmn.io

# API Parser

API to parse excel and PDF files in order to fetch relevant tables from the documents.

## Summary [/document/longshort/summary]
### Summary API [GET]
+ Response 200 (application/json)

        {
            "tables": [ 
                {
                    "table_name": "<name>",
                    "table_data": [{}, {}]
                }, 
                {
                    "table_name": "<name>",
                    "table_data": [{}, {}]
                } 
            ],
            "document_name": "<name>"
        }